### ISSUE TITLE
Question on the RGB - Radar alignment issue

### ISSUE THREAD

**Issue by zzangjinsun** [brade31919/radar_depth#6]
Hello! I have a small question on the RGB and Radar alignment.

I fused RGB and Radar images obtained from tensorboard and got the following results:

![image](https://user-images.githubusercontent.com/20081006/112286214-6fb1b180-8cce-11eb-91c8-3aff4207e388.png)

Some of images show correct overlap (i.e., projection) results but the right-bottom one looks strange.

Is there any idea on this issue? (Problem of calibration? or synchronization?)

Thank you!

**Comment by hz658832** [comment]
do we have imu data which can support to clarify whether the strange projection came from motion disturbance?

LG Haoming

**Comment by brade31919** [comment]
Hi @zzangjinsun ,

Can you provide more details about how you generate these plots? The easiest way to verify this is to plot the data returned by the dataloader directly (e.g. data from [here](https://github.com/brade31919/radar_depth/blob/master/dataset/nuscenes_dataset_torch_new.py#L617)). 
It's possible that this is produced by synchronization issue because they actually didn't have accurate synchronization between LiDAR and Radar in the original nuscenes dataset (They only synced LiDAR and camera). This is less likely to be caused by calibration issue though. I tried the LiDAR and Radar projections myself several times before. If the sensor extrinsics were wrong, we would have encountered this issue on all projects. 

Hi @hz658832 ,
They have IMU data from the original nuscenes database, but I didn't include them into the processed h5 data. 

Sincerely,
Juan-Ting Lin

**Comment by zzangjinsun** [comment]
Thank you for your quick reply @brade31919 !

I just overlaid images from the tensorboard but I think those images are the same as ones from the dataloader.
I also suspect some synchronization issues of the original nuScenes dataset.

Could you keep this issue open for a while? I will dig into the issue and share the results soon!

**Comment by zzangjinsun** [comment]
I checked the nuScenes dataset and concluded that there might be a synchronization issue with Radar for a few samples as shown below:


Good sync:
![image](https://user-images.githubusercontent.com/20081006/113800813-9376fc00-9792-11eb-9892-e36de04e2f00.png)
![image](https://user-images.githubusercontent.com/20081006/113800878-b0abca80-9792-11eb-9244-48b9fe02cda6.png)


Not sure:
![image](https://user-images.githubusercontent.com/20081006/113801039-ff596480-9792-11eb-879c-a16c19b850b1.png)
![image](https://user-images.githubusercontent.com/20081006/113801067-113b0780-9793-11eb-97a3-82d7429c8c6d.png)

(Vertical offset is observed. Maybe due to a speed bump?)

Overall, I think the calibration quality is quite reasonable.

Thx!

**Comment by brade31919** [comment]
Hi @zzangjinsun ,

Thank you for the information! As they described [here](https://www.nuscenes.org/nuscenes#data-collection), it seems that they only handle the synchronization between camera and LiDAR. Therefore, with 13Hz capture frequency, it's quite possible that there exist some synchronization issues between Radar and other sensors. 

Sincerely,
Juan-Ting Lin
