### ISSUE TITLE
About train / val scene numbers

### ISSUE THREAD

**Issue by zzangjinsun** [brade31919/radar_depth#8]
Hi @brade31919 ,

I have a quick question about scene numbers for train / val splits of the released preprocessed dataset.

1. Does the dataset use the exact scene numbers for train / val splits from the following codes?
2. The random seed is always fixed to 100. Did you also use the seed 100 for the dataset? 

https://github.com/brade31919/radar_depth/blob/5e6e75772ff379aac65379a50d4042a7c64c869d/dataset/nuscenes_dataset.py#L116-L128

Thank you very much!

**Comment by brade31919** [comment]
Hi @zzangjinsun,

1. Yes, the processed dataset was created by the code in [that file](https://github.com/brade31919/radar_depth/blob/5e6e75772ff379aac65379a50d4042a7c64c869d/dataset/nuscenes_dataset.py). Since we haven't made sure that the code for creating the processed is ready, we didn't mention it in the README.
2. Yes, I didn't change the random seed. You can check whether the dataset splitting results match the contents in the processed dataset from your side (by checking the images). I am not sure whether `np.random.choice` will have consistent results across different library versions...

Best

**Comment by zzangjinsun** [comment]
I manually checked and concluded that the code is matched with the preprocessed dataset. Thx!
